CREATE TABLE LOGIN_MST(USER_ID NUMBER(5) PRIMARY KEY,LOGIN_ID VARCHAR2(10) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL,USER_NAME VARCHAR(20),
USER_TYPE VARCHAR2(20) CHECK (USER_TYPE='ADMIN' OR USER_TYPE='MEMBER'));

INSERT INTO LOGIN_MST VALUES(101,'USR01','1234567','SUBHA','MEMBER');
INSERT INTO LOGIN_MST VALUES(1011,'ADM01','ADMIN123','SREE','ADMIN');

delete from LOGIN_MST;
CREATE TABLE TOUR_PLAN_MST(TOUR_ID NUMBER(5) PRIMARY KEY,
TOUR_NAME VARCHAR2(10) NOT NULL, STARTING_LOCATION VARCHAR2(20),
PLACES_INCLUDED VARCHAR2(50) NOT NULL,TOURCOST NUMBER(5) NOT NULL,
DISCOUNT_PER NUMBER(5,2), TOUR_DAYS NUMBER(3) NOT NULL);

CREATE TABLE REGISTRATION_DETAILS(TOUR_BOOKING_ID NUMBER(5) PRIMARY KEY,
MEMBER_NAME VARCHAR2(20) NOT NULL, NO_OF_PASSENGERS VARCHAR2(20) DEFAULT '0',
AMOUNT_PAID NUMBER(5,2) NOT NULL, JOURNEY_START_DATE DATE NOT NULL,
TOUR_ID NUMBER(5) REFERENCES TOUR_PLAN_MST(TOUR_ID) NOT NULL,
ISACTIVE NUMBER(1) CHECK(ISACTIVE=1 OR ISACTIVE =0),REMARKS VARCHAR2(50));


COMMIT;